# Generated by Django 4.2.7 on 2023-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0003_remove_course_external_resources_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(related_name='user_course', to='career_toolbox.course', verbose_name='Курсы пользователя'),
        ),
    ]
