# Generated by Django 4.2.7 on 2023-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='users', through='users.UserSkill', to='career_toolbox.skill', verbose_name='Навыки пользователя'),
        ),
    ]
