# Generated by Django 4.2.7 on 2023-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0002_initial'),
        ('users', '0002_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='user_course', to='career_toolbox.course', verbose_name='Курсы пользователя'),
        ),
    ]
