# Generated by Django 4.2.7 on 2023-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_test_unavailable_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_unavailable_until',
            new_name='next_test_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_test_pass_date',
            new_name='test_date',
        ),
    ]
