FROM python:3.11-slim

WORKDIR /app

RUN useradd -m -r -u 100 user

COPY requirements.testing.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chown -R user:user /app && python manage.py collectstatic --noinput && \
    python manage.py migrate

USER user

EXPOSE 8000

CMD ["gunicorn", "tracker_app.wsgi:application", "--bind", "0.0.0.0:8000"]
