version: '3.8'

services:
  db:
    image: postgres:16.1-alpine3.19
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tracker_networks

  backend:
    image: baksbanny/hackaton_tracker_backend:v1.0.0
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    networks:
      - tracker_networks
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: baksbanny/hackaton_tracker_frontend:v1.0.0
    volumes:
      - ../frontend:/app/result_build/
    networks:
      - tracker_networks
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "80:80"
    networks:
      - tracker_networks
    volumes:
      - ../frontend/src:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  postgres_data:
  static_value:
  media_value:

networks:
  tracker_networks:
