# Generated by Django 4.2.7 on 2023-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertest',
            name='point_answer',
            field=models.FloatField(choices=[('V1', '0'), ('V2', '3'), ('V3', '1.5'), ('V4', '1'), ('V5', '0.75')], default='V1', max_length=3, verbose_name='Баллы за ответ'),
        ),
    ]
