# Generated by Django 4.2.7 on 2023-12-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0005_remove_grade_tests'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertest',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answertest_grade', to='career_toolbox.grade', verbose_name='Связанный грейд'),
        ),
    ]
