# Generated by Django 4.2.7 on 2023-12-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_questiontest_skills_questiontest_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontest',
            name='skills',
        ),
    ]
