# Generated by Django 4.2.7 on 2023-12-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description_level',
        ),
    ]
