# Generated by Django 4.2.7 on 2023-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_test_options_remove_test_skills_and_more'),
        ('career_toolbox', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='external_resources',
        ),
        migrations.RemoveField(
            model_name='externalresource',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='externalresource',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='users',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='сourses',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='users',
        ),
        migrations.AddField(
            model_name='course',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_toolbox.externalresource', verbose_name='Внешний ресурс где размещен курс'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_resources',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resourse_projects', to='career_toolbox.externalresource', verbose_name='Ссылки на внешние ресурсы'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='specializations',
        ),
        migrations.AlterField(
            model_name='skill',
            name='base',
            field=models.ManyToManyField(blank=True, related_name='skill_knowledgebase', to='career_toolbox.knowledgebase', verbose_name='Документы из базы знаний'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_toolbox.externalresource', verbose_name='Ссылки на внешние ресурсы'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tests',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_test', to='quiz.test', verbose_name='Тесты по навыкам специализации'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization_grade', to='career_toolbox.grade', verbose_name='Грейды'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='knowledgebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization_base', to='career_toolbox.knowledgebase', verbose_name='База знаний по специальности'),
        ),
        migrations.AddField(
            model_name='project',
            name='specializations',
            field=models.ManyToManyField(related_name='project_specializtion', to='career_toolbox.specialization', verbose_name='Специализации'),
        ),
    ]
