# Generated by Django 4.2.7 on 2023-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='grades',
        ),
        migrations.AddField(
            model_name='specialization',
            name='grades',
            field=models.ManyToManyField(related_name='specialization_grade', to='career_toolbox.grade', verbose_name='Грейды'),
        ),
    ]
