# Generated by Django 4.2.7 on 2023-12-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('career_toolbox', '0003_remove_specialization_grades_specialization_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='tests',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_test', to='quiz.answertest', verbose_name='Грейды для тестов'),
        ),
    ]
