# Generated by Django 4.2.7 on 2023-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0004_remove_course_grades_remove_skill_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tags',
            field=models.ManyToManyField(related_name='knowledgebase_tags', to='career_toolbox.tag', verbose_name='Теги'),
        ),
    ]
