# Generated by Django 4.2.7 on 2023-12-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0004_grade_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='tests',
        ),
    ]
