# Generated by Django 4.2.7 on 2023-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0005_tag_knowledgebase_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='type',
            field=models.CharField(default=1, max_length=150, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(related_name='course_specialization', to='career_toolbox.specialization', verbose_name='Специальности'),
        ),
    ]
