# Generated by Django 4.2.7 on 2023-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0006_alter_tag_options_knowledgebase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courses/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
