# Generated by Django 4.2.7 on 2023-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0007_course_image_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(default=1, upload_to='courses/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
