# Generated by Django 4.2.7 on 2023-12-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_toolbox', '0008_remove_course_image_course_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default=1, upload_to='projects/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
